# -*- coding: utf-8 -*-
"""cse545_twitterscraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MhtL6NH2h8mzsIgZ6BNJvka2MmLKE-df
"""

# !pip install python-twitter

# !pip install tweepy

# !pip install GetOldTweets3

consumer_key = "*********"
consumer_secret = "*********"
access_token_key = "*********"
access_token_secret = "*********"

# Twitter api gives tweets for last 7 days only so from May 07 to May 15 we used Tweepy.
import tweepy
from datetime import datetime

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token_key, access_token_secret)

api = tweepy.API(auth)

def limit_handled(cursor):
    while True:
        try:
            yield cursor.next()
        except tweepy.RateLimitError:
            time.sleep(15 * 60)

public_tweets = api.home_timeline()
for tweet in public_tweets:
    print(tweet.text)

places = api.geo_search(query="USA", granularity="country")
place_id = places[0].id
print("place id for USA {}".format(place_id))

query = ('''#covid19 OR #endthelockdown OR #FreeAmericaNow OR #FreedomIsEssential OR #BacktoWorkAmerica OR 
  #EndTheShutdown OR #neveragain OR #OpenUpAmerica OR #iamgoingbacktowork OR #ReOpenAmerica OR #timetogobacktowork OR  
  #FreeWashingtonState OR #LiberateCalifornia OR  #REOPENWA  OR #MichiganUnitedForLiberty'''%place_id)
max_tweets = 1000
searched_tweets = [status for status in tweepy.Cursor(api.search, q=query).items(max_tweets)]
with open('searched_tweets_{}.txt'.format(datetime.now().strftime('%Y-%m-%d_%H%M%S')), 'w') as fp:
  fp.write(str(searched_tweets))

import time

print("num_tweets={}".format(len(searched_tweets)))
for i in range(10):
  date_time_obj = searched_tweets[i]._json['created_at']
  ts = time.strftime('%Y-%m-%d %H:%M:%S', time.strptime(date_time_obj,'%a %b %d %H:%M:%S +0000 %Y'))
  print(ts)
  print("id = {} and text = {}".format(searched_tweets[i]._json['id'], searched_tweets[i]._json['text']))

# for older tweets we used the library GetOldTweets

import GetOldTweets3 as got
import pandas as pd
def fx(qry, dfrom, duntil, count):
    print(dfrom)
    tweetCriteria = got.manager.TweetCriteria().setQuerySearch(qry).setMaxTweets(count).setSince(dfrom).setUntil(duntil)
    tweets = got.manager.TweetManager.getTweets(tweetCriteria)
    text_tweets = [[tweet.date, tweet.text, tweet.geo, tweet.id, tweet.hashtags] for tweet in tweets]
    tweets_df = pd.DataFrame(text_tweets, columns = ['Datetime', 'Text', 'Location', 'ID', 'Hashtags'])
    print("df size {}".format(tweets_df.shape))
    tweets_df.to_csv('/content/may/{}-{}k-tweets.csv'.format(dfrom, int(count/1000)), sep=',')

for d in range (1,31):
  dfrom = "2020-04-{:02d}".format(d)
  duntil = "2020-04-{:02d}".format(d+1)
  query = '''#covid19 OR #endthelockdown OR #FreeAmericaNow OR #FreedomIsEssential OR #BacktoWorkAmerica OR 
  #EndTheShutdown OR #neveragain OR #OpenUpAmerica OR #iamgoingbacktowork OR #ReOpenAmerica OR #timetogobacktowork OR  
  #FreeWashingtonState OR #LiberateCalifornia OR  #REOPENWA  OR #MichiganUnitedForLiberty'''
  fx(query, dfrom, duntil, 1000)